package tibia.reporting.reportType
{
   public class Type
   {
      
      public static const REPORT_STATEMENT:uint = 1;
      
      public static const REPORT_NAME_REASONS:Array = [new Reason("NAME_REASON_INSULTING_NAME","NAME_REASON_INSULTING_TEXT",0),new Reason("NAME_REASON_RACIST_NAME","NAME_REASON_RACIST_TEXT",0),new Reason("NAME_REASON_SEXUAL_NAME","NAME_REASON_SEXUAL_TEXT",0),new Reason("NAME_REASON_DRUGS_NAME","NAME_REASON_DRUGS_TEXT",0),new Reason("NAME_REASON_HARASSING_NAME","NAME_REASON_HARASSING_TEXT",0),new Reason("NAME_REASON_OBJECTIONABLE_NAME","NAME_REASON_OBJECTIONABLE_TEXT",0),new Reason("NAME_REASON_SENTENCE_NAME","NAME_REASON_SENTENCE_TEXT",1),new Reason("NAME_REASON_FORMATTING_NAME","NAME_REASON_FORMATTING_TEXT",1),new Reason("NAME_REASON_NONSENSE_NAME","NAME_REASON_NONSENSE_TEXT",1),new Reason("NAME_REASON_ADVERTISING1_NAME","NAME_REASON_ADVERTISING1_TEXT",2),new Reason("NAME_REASON_ADVERTISING2_NAME","NAME_REASON_ADVERTISING2_TEXT",2),new Reason("NAME_REASON_ADVERTISING3_NAME","NAME_REASON_ADVERTISING3_TEXT",2),new Reason("NAME_REASON_RELIGIOUS_NAME","NAME_REASON_RELIGIOUS_TEXT",3),new Reason("NAME_REASON_UNFITTING_NAME","NAME_REASON_UNFITTING_TEXT",3),new Reason("NAME_REASON_VIOLATION_NAME","NAME_REASON_VIOLATION_TEXT",4)];
      
      public static const REPORT_STATEMENT_REASONS:Array = [new Reason("STATEMENT_REASON_INSULTING_NAME","STATEMENT_REASON_INSULTING_TEXT",5),new Reason("STATEMENT_REASON_RACIST_NAME","STATEMENT_REASON_RACIST_TEXT",5),new Reason("STATEMENT_REASON_SEXUAL_NAME","STATEMENT_REASON_SEXUAL_TEXT",5),new Reason("STATEMENT_REASON_DRUGS_NAME","STATEMENT_REASON_DRUGS_TEXT",5),new Reason("STATEMENT_REASON_HARASSING_NAME","STATEMENT_REASON_HARASSING_TEXT",5),new Reason("STATEMENT_REASON_OBJECTIONABLE_NAME","STATEMENT_REASON_OBJECTIONABLE_TEXT",5),new Reason("STATEMENT_REASON_SPAM_NAME","STATEMENT_REASON_SPAM_TEXT",6),new Reason("STATEMENT_REASON_NONSENSE_NAME","STATEMENT_REASON_NONSENSE_TEXT",6),new Reason("STATEMENT_REASON_ADVERTISING1_NAME","STATEMENT_REASON_ADVERTISING1_TEXT",7),new Reason("STATEMENT_REASON_ADVERTISING2_NAME","STATEMENT_REASON_ADVERTISING2_TEXT",7),new Reason("STATEMENT_REASON_ADVERTISING3_NAME","STATEMENT_REASON_ADVERTISING3_TEXT",7),new Reason("STATEMENT_REASON_RELIGIOUS_NAME","STATEMENT_REASON_RELIGIOUS_TEXT",8),new Reason("STATEMENT_REASON_OFFTOPIC_NAME","STATEMENT_REASON_OFFTOPIC_TEXT",8),new Reason("STATEMENT_REASON_LANGUAGE_NAME","STATEMENT_REASON_LANGUAGE_TEXT",9),new Reason("STATEMENT_REASON_DISCLOSURE_NAME","STATEMENT_REASON_DISCLOSURE_TEXT",10),new Reason("STATEMENT_REASON_VIOLATION_NAME","STATEMENT_REASON_VIOLATION_TEXT",11),new Reason("STATEMENT_REASON_BUGABUSE_NAME","STATEMENT_REASON_BUGABUSE_TEXT",12),new Reason("STATEMENT_REASON_UNOFFICIAL_NAME","STATEMENT_REASON_UNOFFICIAL_TEXT",13),new Reason("STATEMENT_REASON_PRETENDING_NAME","STATEMENT_REASON_PRETENDING_TEXT",14),new Reason("STATEMENT_REASON_CIPWRONG_NAME","STATEMENT_REASON_CIPWRONG_TEXT",15),new Reason("STATEMENT_REASON_CIPBOYCOTT_NAME","STATEMENT_REASON_CIPBOYCOTT_TEXT",15),new Reason("STATEMENT_REASON_FALSEINFO_NAME","STATEMENT_REASON_FALSEINFO_TEXT",16),new Reason("STATEMENT_REASON_SHARING_NAME","STATEMENT_REASON_SHARING_TEXT",17),new Reason("STATEMENT_REASON_HACKING_NAME","STATEMENT_REASON_HACKING_TEXT",18),new Reason("STATEMENT_REASON_ATTACK_NAME","STATEMENT_REASON_ATTACK_TEXT",19),new Reason("STATEMENT_REASON_LAW_NAME","STATEMENT_REASON_LAW_TEXT",20),new Reason("STATEMENT_REASON_SA_NAME","STATEMENT_REASON_SA_TEXT",20),new Reason("STATEMENT_REASON_COPYRIGHT_NAME","STATEMENT_REASON_COPYRIGHT_TEXT",20)];
      
      public static const REPORT_NAME:uint = 0;
      
      public static const REPORT_BOT_REASONS:Array = [new Reason("BOT_REASON_BOTTING_NAME","BOT_REASON_BOTTING_TEXT",13)];
      
      public static const REPORT_BOT:uint = 2;
       
      
      public function Type()
      {
         super();
      }
   }
}
