package
{
   import mx.resources.ResourceBundle;
   
   public class en_US$ReportWidget_properties extends ResourceBundle
   {
       
      
      public function en_US$ReportWidget_properties()
      {
         super("en_US","ReportWidget");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "NAME_REASON_OBJECTIONABLE_NAME":"generally objectionable",
            "STATEMENT_REASON_OBJECTIONABLE_TEXT":"Statements can be reported if they are grossly distasteful, e.g. cynical remarks about catastrophes.",
            "VALIDATION_SELECT_REASON":"Please select a reason.",
            "STATEMENT_REASON_VIOLATION_TEXT":"Statements can be reported if they support a rule break, encourage others to break a Tibia Rule or announce or imply a violation of the Tibia Rules by the posting player.",
            "NAME_REASON_INSULTING_TEXT":"Names can be reported if they contain very rude and offensive vocabulary or have been created to insult other character names.\n\nExamples:\n\nIllegal - You can report names like:\nStupid Retard, Katie the Moron, Dickhead\n\nLegal - Names like the following are legal and must not be reported:\nNoob, Crazy Guy, Silly Gerta, Charlie the fool",
            "STATEMENT_REASON_ADVERTISING2_NAME":"advertising content which is not related to the game",
            "STATEMENT_REASON_ADVERTISING1_TEXT":"Statements can be reported if they are made to advertise certain goods, services or brands of a third party.",
            "NAME_PROGRESS_STEP_REASON":"Step 1 of 3:\nPlease select the Tibia Rule which is violated.",
            "NAME_REASON_FORMATTING_NAME":"badly formatted words",
            "STATEMENT_REASON_CIPWRONG_NAME":"publishing clearly wrong information about CipSoft",
            "NAME_REASON_ADVERTISING1_NAME":"advertising brand, product or service of a third party",
            "LABEL_COMMENT":"Comment:",
            "NAME_REASON_VIOLATION_NAME":"supporting rule violation",
            "NAME_REASON_OBJECTIONABLE_TEXT":"Names can be reported if they are distasteful and likely to offend people, e.g. references to body fluids, excrements, serious diseases or organised crime, also names of contemporary persons known for serious crimes or inhuman actions.\n\nExamples:\n\nIllegal - You can report names like:\nSnot, Moe the Mongolist, Mafia Hitman, Hitler\n\nLegal - Names like the following are legal and must not be reported:\nVial of Blood, Blind beggar, Genghis Khan",
            "STATEMENT_REASON_HACKING_NAME":"stealing other players\' account or personal data",
            "STATEMENT_REASON_OFFTOPIC_NAME":"off-topic public statements in a channel or board",
            "BTN_PREVIOUS":"Previous",
            "STATEMENT_REASON_COPYRIGHT_NAME":"violating a right of a third party",
            "STATEMENT_REASON_SA_NAME":"violating the Tibia Service Agreement",
            "LABEL_REASON":"Reason:",
            "BTN_NEXT":"Next",
            "NAME_REASON_UNFITTING_NAME":"not fitting Tibia\'s medieval fantasy setting",
            "STATEMENT_REASON_ADVERTISING3_NAME":"advertising a trade for real money",
            "STATEMENT_REASON_ADVERTISING2_TEXT":"Statements can be reported if they contain advertising for all kind of goods and services that are not related to Tibia, e.g. sell my car.",
            "LABEL_NAME":"Name:",
            "STATEMENT_PROGRESS_STEP_CONFIRM":"Step 3 of 3:\nPlease verify your statement report. If everything is correct, click on \"Send\" to forward the report to customer support.",
            "NAME_REASON_FORMATTING_TEXT":"Names can be reported if they lack several spaces or have several weirdly placed spaces.\n\nExamples:\n\nIllegal - You can report names like:\nMikethebigknight, Miketh ebigk night\n\nLegal - Names like the following are legal and must not be reported:\nMike the bigknight, Alba tross",
            "STATEMENT_REASON_CIPWRONG_TEXT":"Statements can be reported if they are made to publish clearly wrong information about CipSoft or its services.",
            "NAME_REASON_ADVERTISING2_NAME":"advertising content which is not related to the game",
            "NAME_REASON_ADVERTISING1_TEXT":"Names can be reported if they contain advertising for worldwide known products, services or companies including titles of other online games.\n\nExamples:\n\nIllegal - You can report names like:\nNike Shoes, Siemens, Frank Google, World of Warcraft\n\nLegal - Names like the following are legal and must not be reported:\nGoddess Nike, Jennifer Lopez, Harry Potter, Real Madrid",
            "NAME_REASON_VIOLATION_TEXT":"Names can be reported if they support a rule break, encourage others to break a Tibia Rule or announce or imply a violation of the Tibia Rules. The same is true for names that have been created to fake an official position.\n\nExamples:\n\nIllegal - You can report names like:\nSellacc, Spam Sponsor, Bothater, God Durin, System Admin, Senator Kate\n\nLegal - Names like the following are legal and must not be reported:\nEvil Thief, Bad Guy, Steve Johnson, God of War, Count Stephan",
            "STATEMENT_REASON_HACKING_TEXT":"Statements can be reported if they prove that a player has tried to steal another player\'s account data or to hack an account or if they contain links to trick other players into downloading malicious software.",
            "STATEMENT_REASON_OFFTOPIC_TEXT":"Statements can be reported if they have been made in the wrong channel or on the wrong board, e.g. trade messages in the help channel.",
            "STATEMENT_REASON_PRETENDING_NAME":"pretending to be CipSoft",
            "STATEMENT_REASON_COPYRIGHT_TEXT":"Statements can be reported if they violate the right of a third party or prove that the right of a third party has been violated or is planned to be violated.",
            "STATEMENT_PROGRESS_STEP_COMMENT":"Step 2 of 3:\nAdd details on the statement report.",
            "STATEMENT_REASON_SA_TEXT":"Statements can be reported if they violate the Tibia Service Agreement or prove that the Tibia Service Agreement has been be violated or is planned to be violated.",
            "STATEMENT_REASON_SEXUAL_NAME":"sexually related",
            "STATEMENT_REASON_DISCLOSURE_NAME":"disclosing personal data of other people",
            "BOT_TITLE":"Report Bot/Macro",
            "NAME_REASON_UNFITTING_TEXT":"Names can be reported if they are completely out of place in Tibia\'s fantasy setting.\n\nExamples:\n\nIllegal - You can report names like:\nSpaceship commander, Remote control, Kalashnikov\n\nLegal - Names like the following are legal and must not be reported:\nSoccer Player, Space observer, Red armchair, Teacher Fred",
            "STATEMENT_REASON_ADVERTISING3_TEXT":"Statements can be reported if they advertise trades of real money for Tibia goods. This includes also offers to buy or sell premium time.",
            "STATEMENT_REASON_RACIST_NAME":"racist",
            "STATEMENT_REASON_ATTACK_NAME":"attacking a CipSoft service",
            "BOT_PROGRESS_STEP_CONFIRM":"Step 3 of 3:\nPlease verify your bot/macro report. If everything is correct, click on \"Send\" to forward the report to customer support.",
            "STATEMENT_REASON_NONSENSE_NAME":"using badly formatted or nonsensical text",
            "NAME_REASON_DRUGS_NAME":"drug-related",
            "NAME_REASON_ADVERTISING3_NAME":"advertising a trade for real money",
            "STATEMENT_REASON_BUGABUSE_NAME":"bug abuse",
            "NAME_REASON_ADVERTISING2_TEXT":"Names can be reported if they contain advertising for content which is not related to the game.\n\nExamples:\n\nIllegal - You can report names like:\nMobile Sale, Buy headset, Sell My Car\n\nLegal - Names like the following are legal and must not be reported:\nMerchant, Potionbuyer",
            "BOT_PROGRESS_STEP_REASON":"Step 1 of 3:\nPlease select the Tibia Rule which is violated.",
            "STATEMENT_REASON_FALSEINFO_NAME":"false information to CipSoft",
            "STATEMENT_REASON_PRETENDING_TEXT":"Statements can be reported if they are made to make other players believe that a player is a CipSoft member or has their powers or legitimation.",
            "NAME_PROGRESS_STEP_CONFIRM":"Step 3 of 3:\nPlease verify your character name report. If everything is correct, click on \"Send\" to forward the report to customer support.",
            "STATEMENT_REASON_SEXUAL_TEXT":"Statements can be reported if they contain references to sex, sexual related body parts or a sexual orientation.",
            "BOT_PROGRESS_STEP_COMMENT":"Step 2 of 3:\nAdd details on the report of \"{0}\".",
            "STATEMENT_REASON_RELIGIOUS_NAME":"religious or political view",
            "STATEMENT_REASON_DISCLOSURE_TEXT":"Statements can be reported if they contain personal data of other people, e.g. email address or phone number.",
            "STATEMENT_REASON_LANGUAGE_NAME":"violating language restriction",
            "STATEMENT_REASON_RACIST_TEXT":"Statements can be reported if they are made to insult a certain country or its inhabitants, a certain nation or an ethnic group.",
            "NAME_REASON_SEXUAL_NAME":"sexually related",
            "STATEMENT_REASON_ATTACK_TEXT":"Statement can be reported if they prove that a player has or wants to attack, disrupt or damage the operation of CipSoft servers, the game or any other part of CipSoft\'s service.",
            "NAME_REASON_NONSENSE_NAME":"nonsensical combination of letters",
            "STATEMENT_REASON_HARASSING_NAME":"harassing",
            "STATEMENT_REASON_NONSENSE_TEXT":"Statements can be reported if they only consist of nonsensical letter combinations like \"asdfsdfskhjkh\" or \"spamspamspam\".",
            "NAME_REASON_DRUGS_TEXT":"Names can be reported if they explicitly relate to drugs and other illegal substances or to well-known drug dealers. The same is true for names that refer to alcoholism.\n\nExamples:\n\nIllegal - You can report names like:\nJunkie, Weedsmoker, Pablo Escobar, Alcoholic\n\nLegal - Names like the following are legal and must not be reported:\nWater pipe, Tobacco Man, Rum bottle, Drunk Dwarf",
            "NAME_REASON_RACIST_NAME":"racist",
            "NAME_REASON_ADVERTISING3_TEXT":"Names can be reported if they contain advertising that imply the selling or buying of Tibia items for real life money.\n\nExamples:\n\nIllegal - You can report names like:\nPremium Seller, Goldseller\n\nLegal - Names like the following are legal and must not be reported:\nTrader Frank, Goldcoin Collector",
            "STATEMENT_REASON_BUGABUSE_TEXT":"Statements can be reported if they prove that a player has abused an obvious game error or any other part of CipSoft\'s service.",
            "NAME_PROGRESS_STEP_COMMENT":"Step 2 of 3:\nAdd details on the report of \"{0}\".",
            "PROMPT_COMMENT":"Please give us more details about your report:",
            "STATEMENT_REASON_CIPBOYCOTT_NAME":"calling a boycott against CipSoft or its services",
            "NAME_REASON_SENTENCE_NAME":"parts of sentence",
            "STATEMENT_REASON_FALSEINFO_TEXT":"Statements can be reported if they prove that a player has intentionally given wrong or misleading information concerning rule violation reports, complaints, bug reports or support requests to CipSoft.",
            "VALIDATION_ENTER_COMMENT":"Please enter a comment.",
            "LABEL_STATEMENT":"Statement:",
            "STATEMENT_REASON_RELIGIOUS_TEXT":"Statements can be reported if they deal with controversial topics like religion and politics.",
            "STATEMENT_REASON_INSULTING_NAME":"insulting",
            "STATEMENT_REASON_LANGUAGE_TEXT":"Statements can be reported if a player repeatedly uses another language than English in the English chat.",
            "BTN_SUBMIT":"Submit",
            "STATEMENT_TITLE":"Report Statement",
            "NAME_REASON_SEXUAL_TEXT":"Names can be reported if they refer to sex, a sexual orientation or intimate body parts. Also names of well-known prostitutes or porn stars may be reported.\n\nExamples:\n\nIllegal - You can report names like:\nSixty-nine, Hetero Guy, Nipple, Breastfeeder\n\nLegal - Names like the following are legal and must not be reported:\nSweet Kiss, Macho, Long Legs",
            "STATEMENT_REASON_DRUGS_NAME":"drug-related",
            "BOT_REASON_BOTTING_NAME":"using unofficial software to play",
            "PROMPT_TRANSLATION":"Please give a translation if you report something that is not in English:",
            "NAME_REASON_NONSENSE_TEXT":"Names can be reported if they contain more than 2 spelling mistakes, use the same string of letters more than twice in a row, or contain an unpronounceable string of letters.\n\nExamples:\n\nIllegal - You can report names like:\nMasster Drruuidd, Bababa, Jasdhschf, Mr Robinson \n\nLegal - Names like the following are legal and must not be reported:\nMaaster Druidd, Babajaba, Jasdoh Sachif, Prof Robinson",
            "STATEMENT_REASON_LAW_NAME":"violating applicable law",
            "LABEL_TRANSLATION":"Translation:",
            "NAME_REASON_HARASSING_NAME":"harassing",
            "STATEMENT_REASON_HARASSING_TEXT":"Statements can be reported if they are made to harass other players or to threaten other players in real life.",
            "NAME_REASON_RACIST_TEXT":"Names can be reported if they reflect prejudice or hatred against people from other races or other countries.\n\nExamples:\n\nIllegal - You can report names like:\nJew hater, White Power, Niggerkiller, Stupid Polak\n\nLegal - Names like the following are legal and must not be reported:\nPolish warrior, Tiago de Brasilia, Black Fighter",
            "STATEMENT_REASON_SHARING_NAME":"account trading or sharing",
            "STATEMENT_REASON_CIPBOYCOTT_TEXT":"Statements can be reported if they are made to ask other players to boycott CipSoft or its services.",
            "STATEMENT_REASON_SPAM_NAME":"excessively repeating identical or similar statements",
            "NAME_REASON_RELIGIOUS_NAME":"religious or political view",
            "STATEMENT_REASON_UNOFFICIAL_NAME":"using unofficial software to play",
            "NAME_REASON_SENTENCE_TEXT":"Names can be reported if they are sentences, recognisable parts of a sentence or if they contain exclamations or greetings.\n\nExamples:\n\nIllegal - You can report names like:\nJohn rox, Knight likes to, Oh my god, Hello\n\nLegal - Names like the following are legal and must not be reported:\nPretty girl, Flowers with thorns, Sesux, Fly",
            "VALIDATION_SPACE_REMAINING":"{0} characters left",
            "STATEMENT_REASON_OBJECTIONABLE_NAME":"generally objectionable",
            "STATEMENT_REASON_VIOLATION_NAME":"supporting a rule violation",
            "NAME_REASON_INSULTING_NAME":"insulting",
            "STATEMENT_REASON_INSULTING_TEXT":"Statements can be reported if they are insulting or contain very offensive vocabulary. Keep in mind that harmless words like \"noob\" might annoy you, but are tolerated and should not be reported.",
            "NAME_TITLE":"Report Name",
            "STATEMENT_REASON_DRUGS_TEXT":"Statements can be reported if they refer to drugs in any way.",
            "STATEMENT_REASON_ADVERTISING1_NAME":"advertising brand, product or service of a third party",
            "BOT_REASON_BOTTING_TEXT":"The player has used unofficial software e.g. a macro program or a so-called tasker or bot, or manipulated the client program.",
            "ERROR_ACKNOWLEDGEMENT_PENDING":"Report failed. Please wait a few minutes before you report again as your previous report is currently still processed.",
            "STATEMENT_REASON_LAW_TEXT":"Statements can be reported if they violate any applicable law or prove that an applicable law has been or or is planned to be violated.",
            "NAME_REASON_HARASSING_TEXT":"Names can be reported if they have been made to harass other players or to threaten other players in real life.\n\nExamples:\n\nIllegal - You can report names like:\nIkillyou Reallife, Wheelchair Marcin\n\nLegal - Names like the following are legal and must not be reported:\nTomurka\'s friend, Bubble Two",
            "STATEMENT_PROGRESS_STEP_REASON":"Step 1 of 3:\nPlease select the Tibia Rule which is violated.",
            "STATEMENT_REASON_SHARING_TEXT":"Statements can be reported if they prove that a player has traded an account, more than one player uses the same account or account data is shared.",
            "STATEMENT_REASON_SPAM_TEXT":"Statements can be reported if they have been repeated excessively on the website or ingame.",
            "NAME_REASON_RELIGIOUS_TEXT":"Names can be reported if they refer to a specific religion or to a person or position that is connected to a certain religion. The same is true for names that express political views or refer to contemporary and well-known politicians.\n\nExamples:\n\nIllegal - You can report names like:\nHindu Master, Jesus Christ, Pope Frank, Anarchist, Lula da Silva\n\nLegal - Names like the following are legal and must not be reported:\nJesus Gonzales, Elfish Priest, God of War, Satan, Abraham Lincoln",
            "STATEMENT_REASON_UNOFFICIAL_TEXT":"Statements can be reported if they prove that a player has manipulated the client program or has used unofficial software, e.g. a macro program or a so-called tasker or bot."
         };
         return _loc1_;
      }
   }
}
