package
{
   import mx.resources.ResourceBundle;
   
   public class en_US$OptionsConfigurationWidget_properties extends ResourceBundle
   {
       
      
      public function en_US$OptionsConfigurationWidget_properties()
      {
         super("en_US","OptionsConfigurationWidget");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "IGNORE_FILTEREDITOR_LBL_PATTERN_COLUMN":"Name",
            "HOTKEY_DLG_RESET_TITLE":"Attention!",
            "INGAMESHOP_ASK_BEFORE_BUYING":"Ask Before Buying Services",
            "HOTKEY_DLG_ADD_NEW_SET":"New Set",
            "MOUSE_LABEL":"Mouse Control",
            "MESSAGE_DLG_RESET_TEXT":"Are you sure that you want to reset all message options to their respective default values?",
            "RENDERER_MAP_SCALE_MAP":"Scale Game Window",
            "RENDERER_PERF_HEADING":"Frame Rate",
            "RENDERER_MAP_HIGHLIGHT":"Highlight Object under Mouse",
            "HOTKEY_DLG_REMOVE_TEXT":"Do you really want to remove the set \"{0}\"? All actions and hotkeys will be lost.",
            "HOTKEY_DLG_EDIT_STATIC":"The hotkey is already assigned to \"{0}\". This assignment cannot be changed.",
            "HOTKEY_DLG_EDIT_CLEAR":" Click \"Clear\" to remove the hotkey from \"{0}\".",
            "RENDERER_LIGHT_HEADING":"Light",
            "IGNORE_FILTEREDITOR_LBL_EMPTY_PATTERN":"<empty>",
            "IGNORE_LBL_WHITE_LIST_GLOBAL":"Global options for allowing messages:",
            "HOTKEY_DLG_REMOVE_TITLE":"Attention!",
            "STATUS_CREATURE_NAME":"Show Name",
            "STATUS_LABEL":"Status",
            "STATUS_PLAYER_NAME":"Show Name",
            "RENDERER_LIGHT_LEVEL_SEPARATOR":"Level Separator",
            "HOTKEY_MODE_CHATMODEOFF":"Chat Off",
            "HOTKEY_DLG_ADD_TEXT":"Please choose the set you want to copy or select \"{0}\" to create a new set using the default settings.",
            "IGNORE_LBL_IGNORE_LIST_GLOBAL":"Global options for ignoring messages:",
            "GENERAL_GENERAL_HEADING":"General",
            "MOUSE_CONTROL_PRESET_CUSTOM":"Custom",
            "HOTKEY_DLG_RESET_TEXT":"Are you sure that you want to reset all bindings in the mode \"{0}\" of the set \"{1}\"?",
            "RENDERER_MAP_HEADING":"Game Window",
            "RENDERER_LIGHT_AMBIENT_BRIGHTNESS":"Ambient Brightness",
            "STATUS_WIDGET_STYLE":"Style",
            "IGNORE_LABEL":"Ignore List",
            "INGAMESHOP_HEADING":"Store",
            "STATUS_CREATURE_FLAGS":"Show Marks",
            "IGNORE_FILTEREDITOR_BTN_ADD":"Add",
            "STATUS_CREATURE_PVPFRAMES":"Show PvP Frames",
            "GENERAL_COMBAT_AUTOCHASEOFF":"Auto Chase Off",
            "GENERAL_OPTIONS_DLG_RESET_TEXT":"Do you really want to reset all options to their default values?\nYou have to leave the options dialogue with Okay to commit the reset",
            "GENERAL_OPTIONS_RESET_HEADING":"Reset Options",
            "MESSAGE_DEFAULT_SET_NAME":"Set {0}",
            "MESSAGE_COLUMN_COLOUR":"Colour",
            "PREMIUM_SHOW_WIDGET":"Show Premium Widget",
            "MESSAGE_CONSOLE_TIMESTAMPS":"Show Timestamps",
            "MOUSE_CONTROL_ACTION_OPEN":"Open",
            "HOTKEY_DLG_EDIT_SELF":"The hotkey is already assigned to \"{0}\". You annot assign the same hotkey twice.",
            "MOUSE_CONTROL_COLUMN_ACTION":"Action",
            "HOTKEY_DLG_ADD_TITLE":"Add Hotkey Set  ",
            "RENDERER_LIGHT_ENABLED":"Enable Light",
            "MOUSE_CONTROL_ACTION_CONTEXT_MENU":"Context Menu",
            "HOTKEY_MODE":"Mode",
            "GENERAL_OPTIONS_RESET":"Reset",
            "RENDERER_PERF_SHOW_FPS":"Show Frame Rate",
            "IGNORE_CHECK_IGNORE_LIST_PRIVATE":"Ignore Private Messages",
            "IGNORE_LBL_IGNORE_LIST_CHARACTERS":"Characters you wish to ignore:",
            "HOTKEY_COLUMN_SECOND_BINDING":"Second Key",
            "IGNORE_LBL_WHITE_LIST_CHARACTERS":"Characters you allow to message you:",
            "HOTKEY_COLUMN_ACTION":"Action",
            "MOUSE_CONTROL_ACTION_SMARTCLICK":"Smart-Click",
            "STATUS_CREATURE_HEADING":"Other Creatures in Game Window",
            "HOTKEY_SETNAME":"Set",
            "GENERAL_OPTIONS_RESET_LABEL":"Reset All Options",
            "HOTKEY_DLG_EDIT_DEFAULT":"Click \"Okay\" to assign the hotkey.",
            "STATUS_WIDGET_SKILL":"Progress Bar",
            "MOUSE_CONTROL_MAPPING":"Mapping",
            "STATUS_CREATURE_STYLE":"Style",
            "MESSAGE_CONSOLE_LEVELS":"Show Levels",
            "HOTKEY_MODE_CHATMODEON":"Chat On",
            "STATUS_RENDERER_STATUS_STYLE_CLASSIC":"Classic",
            "STATUS_RENDERER_STATUS_STYLE_HUD":"HUD",
            "HOTKEY_ADD_SET":"Add",
            "MOUSE_CONTROL_SHOW_ACTION_MOUSE_CURSOR_DESCRIPTION":"(only for Left-Click)",
            "RENDERER_LABEL":"Graphics",
            "HOTKEY_COLUMN_FIRST_BINDING":"First Key",
            "MESSAGE_COLUMN_CHANNEL":"Chat Console",
            "PREMIUM_HEADING":"Premium",
            "MESSAGE_COLUMN_ONSCREEN":"Game Window",
            "IGNORE_CHECK_IGNORE_LIST_YELLING":"Ignore Yelling",
            "RENDERER_MAP_ANTIALIASING":"Antialiasing",
            "RENDERER_PERF_MAX_FPS":"Maximum Frame Rate",
            "HOTKEY_DLG_EDIT_TITLE":"Edit Hotkey for \"{0}\"",
            "STATUS_PLAYER_FLAGS":"Show Marks",
            "STATUS_WIDGET_HEADING":"Status Bar",
            "STATUS_PLAYER_HEADING":"Own Character in Game Window",
            "MOUSE_CONTROL_ACTION_AUTOWALK":"Walk",
            "HOTKEY_RESET_MAPPING":"Restore Defaults",
            "MOUSE_CONTROL_ACTION_LOOK":"Look",
            "HOTKEY_REMOVE_SET":"Remove",
            "MESSAGE_GENERAL_RESET":"Restore Defaults",
            "GENERAL_COMBAT_HEADING":"Combat",
            "TITLE":"Options",
            "GENERAL_OPTIONS_DLG_RESET_TITLE":"Please Confirm!",
            "STATUS_CREATURE_HEALTH":"Show Health",
            "MOUSE_CONTROL_PRESET_RIGHT_SMART_CLICK":"Right Smart-Click (Advanced Classic Control)",
            "MOUSE_CONTROL_ACTION_USE_OR_OPEN":"Use / Open",
            "STATUS_RENDERER_STATUS_STYLE_OFF":"Disabled",
            "MESSAGE_DLG_RESET_TITLE":"Attention!",
            "MESSAGE_LABEL":"Messages",
            "MOUSE_CONTROL_ACTION_TALK":"Talk (NPCs)",
            "HOTKEY_LABEL":"Hotkeys",
            "MOUSE_CONTROL_PRESET_LEFT_SMART_CLICK":"Left Smart-Click",
            "HOTKEY_DLG_ADD_DEFAULT_SET":"<default>",
            "MOUSE_CONTROL_PRESET_KEYMODIFIED_LEFT_CLICK":"Keymodified Left-Click (Stand-Alone Client Standard)",
            "MOUSE_CONTROL_SHOW_ACTION_MOUSE_CURSOR":"Show animated Mouse-Cursor",
            "GENERAL_LABEL":"General",
            "HOTKEY_BINDING_EMPTY":"<empty>",
            "IGNORE_CHECK_WHITE_LIST_ACTIVE":"Activate White List",
            "STATUS_CREATURE_ICONS":"Show NPC Icons",
            "MESSAGE_COLUMN_MODE":"Message",
            "STATUS_PLAYER_STYLE":"Style",
            "IGNORE_FILTEREDITOR_LBL_PERMANENT_COLUMN":"",
            "IGNORE_CHECK_IGNORE_LIST_ACTIVE":"Activate Ignore List",
            "MOUSE_CONTROL_PRESETS":"Presets",
            "MOUSE_CONTROL_ACTION_NONE":"-",
            "STATUS_BOTH_HEADING":"Own Character and Other Creatures",
            "STATUS_PLAYER_HEALTH":"Show Health",
            "MOUSE_CONTROL_COLUMN_MOUSE_BUTTON":"Mouse Button",
            "HOTKEY_DLG_EDIT_DYNAMIC":"The hotkey is already assigned to \"{0}\". Click \"Okay\" to assign it to \"{1}\" instead.",
            "IGNORE_CHECK_WHITE_LIST_BUDDY":"Allow VIPs to message you",
            "MOUSE_CONTROL_ACTION_ATTACK_OR_TALK":"Attack / Talk (NPCs)",
            "IGNORE_FILTEREDITOR_BTN_DEL":"Remove",
            "MOUSE_CONTROL_RESET":"Restore Defaults",
            "STATUS_PLAYER_MANA":"Show Mana"
         };
         return _loc1_;
      }
   }
}
