package
{
   import mx.resources.ResourceBundle;
   
   public class en_US$StaticAction_properties extends ResourceBundle
   {
       
      
      public function en_US$StaticAction_properties()
      {
         super("en_US","StaticAction");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "GAME_EQUIP_GENERIC_OBJECT":"the Object",
            "MISC_AUTOFIT_GAMEWINDOW":"Auto Adjust Game Window",
            "GAME_USE_TARGET_SELF":"Use {0} on Yourself",
            "MISC_ATTACK_NEXT":"Attack Next Target",
            "MISC_MAPPING_NEXT":"Next Hotkey & Action Button Set",
            "MISC_TOGGLE_ACTIONBAR_TOP":"Open / Close Action Bar Top",
            "MMAP_MOVE_UP":"Scroll Minimap North",
            "MISC_EXPIRE_ONSCREEN_MESSAGE":"Clear Oldest Message",
            "MMAP_MOVE_LEFT":"Scroll Minimap West",
            "MISC_COMBAT_CHASE":"Toggle Chase Mode",
            "CHAT_SEND_TEXT":"Send Text",
            "CHAT_MOVE_CURSOR_RIGHT":"Set Cursor Right",
            "CHAT_TEXT_INPUT":"Text Input",
            "MISC_TOGGLE_STATUSBAR":"Open / Close Status Bar",
            "MISC_SHOW_EDIT_IGNORELIST":"Open Ignore List",
            "MMAP_ZOOM_IN":"Zoom In Minimap",
            "UNKNOWN_ACTION":"<Unknown>",
            "PLAYER_MOVE_UP_LEFT":"Move Character North-West",
            "PLAYER_MOVE_DOWN_RIGHT":"Move Character South-East",
            "CHAT_CHANNEL_CLOSE_PRIMARY":"Close Current Channel",
            "PLAYER_MOVE_DOWN":"Move Character South",
            "MISC_ROOT_CONTAINER":"Open / Close Root Container",
            "MISC_SHOW_WIDGET_COMBATCONTROL":"Open / Close Combat Controls",
            "GAME_TALK":"Say \"{0}\"",
            "MMAP_ZOOM_OUT":"Zoom Out Minimap",
            "MISC_COMBAT_PVP_RED_FIST":"Switch to PvP Mode Red Fist",
            "PLAYER_CANCEL":"Stop All Actions",
            "PLAYER_MOVE_UP":"Move Character North",
            "MMAP_CENTER":"Centre Minimap",
            "CHAT_CHANNEL_SERVER":"Switch to Server Log",
            "MISC_COMBAT_OFFENSIVE":"Switch to Offensive Fighting",
            "MISC_TRIGGER_SLOT":"Use Action Button {0}",
            "MISC_SHOW_WIDGET_BUDDYLIST":"Open / Close VIP List",
            "PLAYER_MOVE_UP_RIGHT":"Move Character North-East",
            "GAME_MOVE_UNMOVEABLE":"You cannot move this object",
            "PLAYER_MOVE_DOWN_LEFT":"Move Character South-West",
            "CHAT_MOVE_CURSOR_HOME":"Set Cursor Home",
            "MISC_SHOW_WIDGET_SPELLLIST":"Open / Close Spell List ",
            "MISC_TOGGLE_MAPPING_MODE":"Toggle Chat Mode",
            "GAME_EQUIP_UNEQUIP":"Unequip {0}",
            "MISC_TOGGLE_SIDEBAR_OUTER_RIGHT":"Open / Close Side Bar Outer Right",
            "PLAYER_MOVE_RIGHT":"Move Character East",
            "PLAYER_MOUNT":"Mount / Dismount",
            "CHAT_COPYPASTE_COPY":"Copy Selected Text",
            "CHAT_COPYPASTE_SELECT":"Select All Text",
            "CHAT_CHANNEL_PREV":"Switch to Previous Channel",
            "MISC_SHOW_WIDGET_BATTLELIST":"Open / Close Battle List",
            "MMAP_LAYER_UP":"Scroll Minimap Floor Up",
            "PLAYER_TURN_DOWN":"Turn Character South",
            "PLAYER_MOVE_LEFT":"Move Character West",
            "CHAT_DELETE_PREV":"Delete Previous Text",
            "MISC_COMBAT_BALANCED":"Switch to Balanced Fighting",
            "MISC_TOGGLE_SIDEBAR_INNER_RIGHT":"Open / Close Side Bar Inner Right",
            "CHAT_CHANNEL_CLOSE_SECONDARY":"Close Secondary Channel Window",
            "CHAT_CHANNEL_OPEN":"Open New Channel",
            "CHAT_HISTORY_PREV":"Show Previous Message Entry",
            "PLAYER_TURN_RIGHT":"Turn Character East",
            "MISC_SHOW_EDIT_HOTKEY":"Open Hotkey Options",
            "GAME_USE_TARGET_CROSSHAIR":"Use {0} with Crosshair",
            "MISC_SHOW_QUEST_LOG":"Open Quest Log",
            "MISC_SEND_BUG_REPORT":"Open Bug Report Dialog",
            "MISC_SHOW_WIDGET_MINIMAP":"Open / Close Minimap",
            "CHAT_MOVE_CURSOR_END":"Set Cursor End",
            "MISC_LOGOUT_CHARACTER":"Logout Character",
            "MISC_TOGGLE_ACTIONBAR_RIGHT":"Open / Close Action Bar Right ",
            "MISC_SHOW_EDIT_GENERAL":"Open General Options",
            "MISC_SHOW_EDIT_MESSAGE":"Open Message Options",
            "MISC_TOGGLE_SIDEBAR_INNER_LEFT":"Open / Close Side Bar Inner Left",
            "MISC_COMBAT_DEFENSIVE":"Switch to Defensive Fighting",
            "PLAYER_TURN_LEFT":"Turn Character West",
            "CHAT_CHANNEL_NEXT":"Switch to Next Channel",
            "MMAP_MOVE_RIGHT":"Scroll Minimap East",
            "MISC_SHOW_CHARACTER":"Open Character Profile",
            "GAME_ERROR":"Error",
            "CHAT_DELETE_NEXT":"Delete Following Text",
            "MISC_TOGGLE_ACTIONBAR_BOTTOM":"Open / Close Action Bar Bottom",
            "MISC_ATTACK_PREV":"Attack Previous Target",
            "CHAT_CHANNEL_DEFAULT":"Switch to Local Chat",
            "MISC_SHOW_OUTFIT":"Open Select Outfit Dialog",
            "MISC_MAPPING_PREV":"Previous Hotkey & Action Button Set",
            "GAME_EQUIP_EQUIP":"Equip {0}",
            "MMAP_LAYER_DOWN":"Scroll Minimap Floor Down",
            "MISC_SHOW_WIDGET_GENERALBUTTONS":"Open / Close General Controls",
            "CHAT_MOVE_CURSOR_LEFT":"Set Cursor Left",
            "CHAT_HISTORY_NEXT":"Show Next Message Entry",
            "MISC_COMBAT_PVP_DOVE":"Switch to PvP Mode Dove",
            "CHAT_COPYPASTE_CUT":"Cut Selected Text",
            "MMAP_MOVE_DOWN":"Scroll Minimap South",
            "MISC_COMBAT_PVP_YELLOW_HAND":"Switch to PvP Mode Yellow Hand",
            "GAME_USE_GENERIC_OBJECT":"the object",
            "MISC_TOGGLE_SIDEBAR_OUTER_LEFT":"Open / Close Side Bar Outer Left",
            "MISC_SHOW_EDIT_STATUS":"Open Status Options",
            "MISC_SHOW_EDIT_RENDERER":"Open Graphics Options",
            "MISC_CHANGE_CHARACTER":"Change Character",
            "MISC_SHOW_WIDGET_BODY":"Open / Close Inventory",
            "CHAT_COPYPASTE_INSERT":"Paste Text",
            "MISC_TOGGLE_ACTIONBAR_LEFT":"Open / Close Action Bar Left",
            "MISC_COMBAT_PVP_WHITE_HAND":"Switch to PvP Mode White Hand",
            "MISC_COMBAT_SECURE":"Toggle Secure Mode",
            "PLAYER_TURN_UP":"Turn Character North",
            "GAME_SPELL":"Cast {0}",
            "MISC_TOGGLE_LOCK_MODE":"Toggle Lock Mode",
            "GAME_USE_TARGET_ATTACK":"Use {0} on Attack Target"
         };
         return _loc1_;
      }
   }
}
