package
{
   import mx.resources.ResourceBundle;
   
   public class en_US$MarketWidget_properties extends ResourceBundle
   {
       
      
      public function en_US$MarketWidget_properties()
      {
         super("en_US","MarketWidget");
      }
      
      override protected function getContent() : Object
      {
         var _loc1_:Object = {
            "CATEGORY_BOOTS_LABEL":"Boots",
            "KIND_SELECT":"Please Select",
            "MARKET_EDIT_TOTALPRICE_LABEL":"Total Price including Fees:",
            "RESTRICT_ONE_HANDED_LABEL":"One-handed",
            "DETAIL_FIELD_ARMOR":"Armor",
            "RESTRICT_DEPOT_TOOLTIP":"Restrict list to the objects in your depot.",
            "RESTRICT_PROFESSION_LABEL":"Voc.",
            "CATEGORY_HELMETS_HATS_LABEL":"Helmets and Hats",
            "DETAIL_FIELD_RESTRICT_LEVEL":"Minimum Required Level",
            "OWN_OFFERS_VIEW_LABEL":"Current Offers",
            "MARKET_EDIT_ACCOUNTBALANCE_LABEL":"Your Gold:",
            "DETAIL_FIELD_CAPACITY":"Capacity",
            "TYPE_UNKNOWN":"Unknown",
            "MARKET_DETAILS_VIEW_LABEL":"Details",
            "MARKET_EDIT_KIND_LABEL":"Offer Type:",
            "REASON_EXPIRED":"Expired",
            "RESTRICT_LEVEL_LABEL":"Level",
            "MARKET_DIALOG_CANCEL_TEXT":"Are you sure you want to cancel the offer?",
            "CATEGORY_OTHERS_LABEL":"Others",
            "CATEGORY_CLUBS_LABEL":"Clubs",
            "OFFERS_VIEW_OFFER_ABOVE":"Dubious Offer: This offer is at least 25% above the average market value.",
            "MARKET_STATISTICS_VIEW_LABEL":"Statistics",
            "OWN_OFFERS_VIEW_SELLCANCEL":"Cancel",
            "OFFERS_VIEW_OFFER_BELOW":"Dubious Offer: This offer is at least 25% below the average market value.",
            "OWN_OFFERS_VIEW_BUYOFFERS":"Buy Offers",
            "MARKET_EDIT_AMOUNT_LABEL":"Amount:",
            "CATEGORY_AMMUNITION_LABEL":"Ammunition",
            "OWN_HISTORY_VIEW_LABEL":"Offer History",
            "CATEGORY_TIBIA_COINS":"Tibia Coins",
            "MARKET_OFFERS_VIEW_SELLACCEPT":"Buy Now",
            "OFFERS_VIEW_COLUMN_AMOUNT":"Amount",
            "OFFERS_VIEW_COLUMN_NAME":"Character Name",
            "OFFERS_VIEW_COLUMN_PIECEPRICE":"Piece Price",
            "CATEGORY_TOOLS_LABEL":"Tools",
            "RESTRICT_ANY_HAND_LABEL":"Any Weapon",
            "CATEGORY_AMULETS_LABEL":"Amulets",
            "CATEGORY_FOOD_LABEL":"Food",
            "MARKET_OFFERS_LABEL":"Market Offers",
            "CATEGORY_LEGS_LABEL":"Legs",
            "REASON_ACCEPTED_SELL_OFFER":"Sold",
            "KIND_BUY_OFFER":"Buy",
            "MARKET_EDIT_PIECEPRICE_LABEL":"Piece Price:",
            "CATEGORY_ARMORS_LABEL":"Armors",
            "REASON_ACCEPTED_BUY_OFFER":"Bought",
            "TIMESTAMP_UNKNOWN":"Unknown",
            "RESTRICT_DEPOT_LABEL":"Show Depot Only",
            "OFFERS_VIEW_COLUMN_TYPEID":"Item",
            "KIND_SELL_OFFER":"Sell",
            "MARKET_OFFERS_VIEW_BUYACCEPT":"Sell Now",
            "NAME_FILTER_EDITOR_LABEL":"Search",
            "MARKET_STATISTICS_VIEW_AVERAGE":"Average Price",
            "MARKET_DIALOG_ACCEPT_TEXT":"Please select the amount of objects for the transaction:",
            "CATEGORY_VALUABLES_LABEL":"Valuables",
            "CATEGORY_DISTANCE_WEAPONS_LABEL":"Distance Weapons",
            "CATEGORY_AXES_LABEL":"Axes",
            "DETAIL_FIELD_RESTRICT_MAGICLEVEL":"Minimum Required Magic Level",
            "CATEGORY_RINGS_LABEL":"Rings",
            "OWN_HISTORY_VIEW_SELLOFFERS":"Sell Offers",
            "MARKET_EDIT_CREATE_LABEL":"Create Now",
            "MARKET_STATISTICS_VIEW_MAXIMUM":"Highest Price",
            "DETAIL_FIELD_PROTECTION":"Protection",
            "CATEGORY_SWORDS_LABEL":"Swords",
            "RESTRICT_PROFESSION_TOOLTIP":"Restrict list to objects that match your vocation.",
            "DETAIL_FIELD_RESTRICT_PROFESSION":"Professions",
            "DETAIL_FIELD_WEAPON_TYPE":"Weapon Type",
            "REASON_ACTIVE":"Active",
            "MARKET_EDIT_ANONYMOUS_LABEL":"Anonymous:",
            "RESTRICT_LEVEL_TOOLTIP":"Restrict list to objects that match your level.",
            "CATEGORY_CONTAINERS_LABEL":"Containers",
            "DETAIL_FIELD_DESCRIPTION":"Description",
            "MARKET_EDIT_COINS_LABEL":"Your Tibia Coins:",
            "MARKET_OFFERS_VIEW_SELLOFFERS":"Sell Offers",
            "OWN_OFFERS_LABEL":"My Offers",
            "MARKET_DIALOG_GENERIC_TITLE":"Market",
            "OFFERS_VIEW_COLUMN_TOTALPRICE":"Total Price",
            "MARKET_STATISTICS_VIEW_MINIMUM":"Lowest Price",
            "REASON_CANCELLED":"Cancelled",
            "DETAIL_FIELD_DEFENCE":"Defence",
            "OWN_HISTORY_VIEW_BUYOFFERS":"Buy Offers",
            "DETAIL_FIELD_SKILLBOOST":"Skill Boost",
            "OWN_OFFERS_VIEW_BUYCANCEL":"Cancel",
            "TITLE":"Market",
            "CATEGORY_DECORATION_LABEL":"Decoration",
            "DETAIL_FIELD_RUNE_SPELL":"Spell",
            "MARKET_STATISTICS_VIEW_SELLOFFERS":"Sell Offers",
            "CATEGORY_META_WEAPONS_LABEL":"Weapons",
            "DETAIL_FIELD_WEIGHT":"Weight",
            "OWN_OFFERS_VIEW_SELLOFFERS":"Sell Offers",
            "DETAIL_FIELD_USES":"Charges",
            "MARKET_STATISTICS_VIEW_TOTALTRANSACTIONS":"Number of Transactions",
            "OFFERS_VIEW_COLUMN_TERMINATIONTREASON":"Termination Trigger",
            "CATEGORY_FILTER_EDITOR_LABEL":"Browse",
            "DETAIL_FIELD_ATTACK":"Attack",
            "CATEGORY_WANDS_RODS_LABEL":"Wands and Rods",
            "MARKET_OFFERS_VIEW_BUYOFFERS":"Buy Offers",
            "REASON_UNKNOWN":"Unknown",
            "MARKET_STATISTICS_VIEW_BUYOFFERS":"Buy Offers",
            "MARKET_EDIT_LABEL":"Create New Offer",
            "CATEGORY_POTIONS_LABEL":"Potions",
            "MARKET_EDIT_CUMULATIVEPRICE_LABEL":"Total Price:",
            "MARKET_OFFERS_VIEW_LABEL":"Offers",
            "MARKET_STATISTICS_VIEW_EMPTY":"No information available.",
            "DETAIL_FIELD_EXPIRE":"Expires after",
            "OFFERS_VIEW_COLUMN_TIMESTAMP":"Ends at",
            "MARKET_OFFERS_NO_TYPE":"No item selected.",
            "REASON_ACCEPTED_GENERIC":"Accepted",
            "CATEGORY_SHIELDS_LABEL":"Shields",
            "RESTRICT_TWO_HANDED_LABEL":"Two-handed",
            "CATEGORY_RUNES_LABEL":"Runes"
         };
         return _loc1_;
      }
   }
}
